"""What gets indexed, and what never does.

Ignore layers, most specific first (docs/system-design.md §6.2):

1. config ``index.exclude`` — an explicit "no"
2. config ``index.include`` — an explicit "yes", which overrides layers 3 and 4 so a
   project can deliberately index a vendored subtree
3. built-in defaults — ``.git/``, ``node_modules/``, lockfiles, minified output, media
4. ``.gitignore``, then ``.hearthignore``

Then size, binary and generated-code checks.

**Secret files are never indexed, at any layer, and no config can re-enable them.** An
``index.include`` entry cannot override the denylist: a `.env` reaching the index would
put credentials into a database, into retrieval results, and from there into a prompt.
That is a one-way mistake, so the check is an invariant rather than a default
(docs/safety-and-tool-use.md §10).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import PurePosixPath

import pathspec

#: Directories that are never worth indexing. Matched on any path segment.
DEFAULT_IGNORED_DIRS: frozenset[str] = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        ".venv",
        "venv",
        "env",
        "node_modules",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        ".nox",
        "dist",
        "build",
        "target",
        ".next",
        ".nuxt",
        ".svelte-kit",
        "vendor",
        ".gradle",
        ".idea",
        ".vscode",
        "site-packages",
        ".terraform",
    }
)

#: Glob patterns for files that are noise: lockfiles, minified bundles, maps, media.
DEFAULT_IGNORED_GLOBS: tuple[str, ...] = (
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "uv.lock",
    "Cargo.lock",
    "composer.lock",
    "Gemfile.lock",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.bmp",
    "*.ico",
    "*.svg",
    "*.webp",
    "*.mp3",
    "*.mp4",
    "*.mov",
    "*.avi",
    "*.wav",
    "*.pdf",
    "*.zip",
    "*.tar",
    "*.gz",
    "*.bz2",
    "*.xz",
    "*.7z",
    "*.rar",
    "*.jar",
    "*.war",
    "*.class",
    "*.so",
    "*.dylib",
    "*.dll",
    "*.exe",
    "*.bin",
    "*.o",
    "*.a",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "*.wasm",
    "*.db",
    "*.sqlite",
    "*.sqlite3",
    "*.woff",
    "*.woff2",
    "*.ttf",
    "*.otf",
    "*.eot",
)

#: Files that must never be indexed. Not configurable, not overridable.
SECRET_FILE_PATTERNS: tuple[str, ...] = (
    ".env",
    ".env.*",
    "*.env",
    "env.local",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
    "*.jks",
    "*.keystore",
    "id_rsa*",
    "id_dsa*",
    "id_ecdsa*",
    "id_ed25519*",
    "*.ppk",
    "credentials",
    "credentials.*",
    "*credentials.json",
    ".npmrc",
    ".pypirc",
    ".netrc",
    "_netrc",
    ".htpasswd",
    "*.tfstate",
    "*.tfstate.*",
    "secrets.*",
    "*.secrets",
    "service-account*.json",
    ".aws/credentials",
    ".ssh/*",
)

#: Markers that indicate machine-generated code.
_GENERATED_MARKERS: tuple[re.Pattern[str], ...] = (
    re.compile(r"@generated\b"),
    re.compile(r"\bDO NOT EDIT\b", re.IGNORECASE),
    re.compile(r"\bCode generated by\b", re.IGNORECASE),
    re.compile(r"\bautogenerated\b", re.IGNORECASE),
    re.compile(r"\bgenerated by the protocol buffer compiler\b", re.IGNORECASE),
)

#: Generated files are detected in the first N bytes; markers live in the header.
_GENERATED_SNIFF_BYTES = 4096

#: Average line length above this suggests minified or generated output.
_MAX_AVERAGE_LINE_LENGTH = 300


@dataclass(frozen=True)
class FilterDecision:
    """Why a path was kept or dropped. ``reason`` is for `--explain` and doctor output."""

    include: bool
    reason: str = ""

    def __bool__(self) -> bool:
        return self.include


@dataclass
class FilterStats:
    """Counters, so indexing can report what it skipped and why."""

    scanned: int = 0
    excluded_dir: int = 0
    excluded_glob: int = 0
    excluded_secret: int = 0
    excluded_config: int = 0
    excluded_gitignore: int = 0
    too_large: int = 0
    binary: int = 0
    generated: int = 0
    kept: int = 0
    by_reason: dict[str, int] = field(default_factory=dict)

    def record(self, decision: FilterDecision) -> None:
        self.scanned += 1
        if decision.include:
            self.kept += 1
        else:
            self.by_reason[decision.reason] = self.by_reason.get(decision.reason, 0) + 1


class PathFilter:
    """Decides which paths are indexable, before any file is opened."""

    def __init__(
        self,
        *,
        exclude: tuple[str, ...] | list[str] = (),
        include: tuple[str, ...] | list[str] = (),
        gitignore: pathspec.PathSpec[pathspec.Pattern] | None = None,
        hearthignore: pathspec.PathSpec[pathspec.Pattern] | None = None,
        respect_defaults: bool = True,
    ) -> None:
        self._respect_defaults = respect_defaults
        self._default_globs = _compile(DEFAULT_IGNORED_GLOBS) if respect_defaults else None
        self._secret = _compile(SECRET_FILE_PATTERNS)
        self._exclude = _compile(exclude) if exclude else None
        self._include = _compile(include) if include else None
        self._gitignore = gitignore
        self._hearthignore = hearthignore

    def decide(self, relative_path: str) -> FilterDecision:
        """Whether a workspace-relative POSIX path should be indexed.

        Precedence, highest first:

        1. **Secret denylist** — absolute, and nothing below can re-enable it.
        2. **config exclude** — the user's explicit "no" beats their explicit "yes",
           mirroring deny-beats-allow in the policy engine.
        3. **config include** — an explicit "yes" overrides the built-in defaults and the
           ignore files, which is what lets a project index a vendored subtree on purpose.
        4. built-in default directories and globs.
        5. ``.gitignore``, then ``.hearthignore``.
        """
        path = PurePosixPath(relative_path)

        if self._secret.match_file(relative_path) or self._secret.match_file(path.name):
            return FilterDecision(False, "secret-file")

        if self._exclude is not None and self._exclude.match_file(relative_path):
            return FilterDecision(False, "config-exclude")

        if self._include is not None:
            if self._include.match_file(relative_path):
                return FilterDecision(True)
            return FilterDecision(False, "not-in-include")

        if self._respect_defaults:
            for part in path.parts[:-1]:
                if part in DEFAULT_IGNORED_DIRS:
                    return FilterDecision(False, f"ignored-dir:{part}")

            if self._default_globs is not None and self._default_globs.match_file(relative_path):
                return FilterDecision(False, "ignored-glob")

        if self._gitignore is not None and self._gitignore.match_file(relative_path):
            return FilterDecision(False, "gitignore")
        if self._hearthignore is not None and self._hearthignore.match_file(relative_path):
            return FilterDecision(False, "hearthignore")

        return FilterDecision(True)

    def is_secret(self, relative_path: str) -> bool:
        """Public so the read tools can refuse the same set (docs/safety-and-tool-use.md §10)."""
        name = PurePosixPath(relative_path).name
        return bool(self._secret.match_file(relative_path) or self._secret.match_file(name))


def load_ignore_file(path_text: str | None) -> pathspec.PathSpec[pathspec.Pattern] | None:
    """Compile gitignore-syntax text into a spec. None for empty or missing input."""
    if not path_text:
        return None
    return pathspec.PathSpec.from_lines("gitignore", path_text.splitlines())


def _compile(patterns: tuple[str, ...] | list[str]) -> pathspec.PathSpec[pathspec.Pattern]:
    return pathspec.PathSpec.from_lines("gitignore", patterns)


# ----------------------------------------------------------------- content checks


def is_too_large(size_bytes: int, *, max_bytes: int) -> bool:
    return size_bytes > max_bytes


def looks_generated(text: str) -> bool:
    """Whether a file looks machine-generated.

    Generated files are indexed as metadata only, not chunked: they bloat the index and
    almost never answer a question worth asking (docs/system-design.md §6.2).
    """
    header = text[:_GENERATED_SNIFF_BYTES]
    if any(marker.search(header) for marker in _GENERATED_MARKERS):
        return True

    lines = text.splitlines()
    if len(lines) >= 5:
        average = sum(len(line) for line in lines) / len(lines)
        if average > _MAX_AVERAGE_LINE_LENGTH:
            return True
    return False
