# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
_SCHEMA = b'\x0a\x0cfake-descriptor-bytes-here-not-real-content'
def _builder(): return _SCHEMA
